# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: revenue.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='revenue.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rrevenue.proto\"6\n\x0eInitRequestMsg\x12\x18\n\x10\x65pisode_duration\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\t\"M\n\x0cInitReplyMsg\x12\x0e\n\x06prices\x18\x01 \x03(\x05\x12\x16\n\x0etotal_capacity\x18\x02 \x01(\x05\x12\x15\n\rn_subepisodes\x18\x03 \x01(\x05\"3\n\x0bSetPriceMsg\x12\x15\n\rreset_episode\x18\x01 \x01(\x08\x12\r\n\x05price\x18\x02 \x01(\x05\"\xa8\x01\n\x07InfoMsg\x12\x13\n\x0b\x65pisode_end\x18\x01 \x01(\x08\x12\x16\n\x0esubepisode_end\x18\x02 \x01(\x08\x12\x10\n\x08\x63\x61pacity\x18\x03 \x01(\x05\x12\x18\n\x10subepisodes_left\x18\x04 \x01(\x05\x12\x16\n\x0elatest_clients\x18\x05 \x01(\x05\x12\x15\n\rlatest_reward\x18\x06 \x01(\x05\x12\x15\n\rtotal_revenue\x18\x07 \x01(\x05\" \n\rSimpleInfoMsg\x12\x0f\n\x07\x63lients\x18\x01 \x03(\x05\x62\x06proto3')
)




_INITREQUESTMSG = _descriptor.Descriptor(
  name='InitRequestMsg',
  full_name='InitRequestMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='episode_duration', full_name='InitRequestMsg.episode_duration', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='InitRequestMsg.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=71,
)


_INITREPLYMSG = _descriptor.Descriptor(
  name='InitReplyMsg',
  full_name='InitReplyMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prices', full_name='InitReplyMsg.prices', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_capacity', full_name='InitReplyMsg.total_capacity', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n_subepisodes', full_name='InitReplyMsg.n_subepisodes', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=150,
)


_SETPRICEMSG = _descriptor.Descriptor(
  name='SetPriceMsg',
  full_name='SetPriceMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reset_episode', full_name='SetPriceMsg.reset_episode', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='SetPriceMsg.price', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=203,
)


_INFOMSG = _descriptor.Descriptor(
  name='InfoMsg',
  full_name='InfoMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='episode_end', full_name='InfoMsg.episode_end', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subepisode_end', full_name='InfoMsg.subepisode_end', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='capacity', full_name='InfoMsg.capacity', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subepisodes_left', full_name='InfoMsg.subepisodes_left', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latest_clients', full_name='InfoMsg.latest_clients', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latest_reward', full_name='InfoMsg.latest_reward', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_revenue', full_name='InfoMsg.total_revenue', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=374,
)


_SIMPLEINFOMSG = _descriptor.Descriptor(
  name='SimpleInfoMsg',
  full_name='SimpleInfoMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clients', full_name='SimpleInfoMsg.clients', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=376,
  serialized_end=408,
)

DESCRIPTOR.message_types_by_name['InitRequestMsg'] = _INITREQUESTMSG
DESCRIPTOR.message_types_by_name['InitReplyMsg'] = _INITREPLYMSG
DESCRIPTOR.message_types_by_name['SetPriceMsg'] = _SETPRICEMSG
DESCRIPTOR.message_types_by_name['InfoMsg'] = _INFOMSG
DESCRIPTOR.message_types_by_name['SimpleInfoMsg'] = _SIMPLEINFOMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InitRequestMsg = _reflection.GeneratedProtocolMessageType('InitRequestMsg', (_message.Message,), dict(
  DESCRIPTOR = _INITREQUESTMSG,
  __module__ = 'revenue_pb2'
  # @@protoc_insertion_point(class_scope:InitRequestMsg)
  ))
_sym_db.RegisterMessage(InitRequestMsg)

InitReplyMsg = _reflection.GeneratedProtocolMessageType('InitReplyMsg', (_message.Message,), dict(
  DESCRIPTOR = _INITREPLYMSG,
  __module__ = 'revenue_pb2'
  # @@protoc_insertion_point(class_scope:InitReplyMsg)
  ))
_sym_db.RegisterMessage(InitReplyMsg)

SetPriceMsg = _reflection.GeneratedProtocolMessageType('SetPriceMsg', (_message.Message,), dict(
  DESCRIPTOR = _SETPRICEMSG,
  __module__ = 'revenue_pb2'
  # @@protoc_insertion_point(class_scope:SetPriceMsg)
  ))
_sym_db.RegisterMessage(SetPriceMsg)

InfoMsg = _reflection.GeneratedProtocolMessageType('InfoMsg', (_message.Message,), dict(
  DESCRIPTOR = _INFOMSG,
  __module__ = 'revenue_pb2'
  # @@protoc_insertion_point(class_scope:InfoMsg)
  ))
_sym_db.RegisterMessage(InfoMsg)

SimpleInfoMsg = _reflection.GeneratedProtocolMessageType('SimpleInfoMsg', (_message.Message,), dict(
  DESCRIPTOR = _SIMPLEINFOMSG,
  __module__ = 'revenue_pb2'
  # @@protoc_insertion_point(class_scope:SimpleInfoMsg)
  ))
_sym_db.RegisterMessage(SimpleInfoMsg)


# @@protoc_insertion_point(module_scope)
